// AUTO-GENERATED by `npm run preview:wire` — placeholder.
// Reason: manifest is empty — produced an empty COMPONENT_MAP
import * as React from "react";
import { UnknownComponentFallback } from "./fallbacks.tsx";

export const COMPONENT_MAP: Record<string, React.ComponentType<any>> = {};

export function resolveComponent(id: string): React.ComponentType<any> {
  return (_props: any) => React.createElement(UnknownComponentFallback, { id });
}
