// AUTO-GENERATED by `npm run preview:wire` — do not hand-edit.
// Side-effect imports of each DS's global stylesheet, loaded once by
// web/src/main.tsx after tokens.css. Empty when no DS declares
// `styles.globalStylesheets` in manifest.config.json.
export {};
